---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yml|yaml|talismanrc)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.26.0
    hooks:
      - id: talisman-commit
